### ISSUE TITLE
Publication par erreur de LCC 269 sur lescastcodeurs.com ?

### ISSUE THREAD

**Issue by marcwrobel** [lescastcodeurs/lescastcodeurs.com#101]
Salut @glaforge, j'ai l'impression que tu as publié par erreur LCC 269 sur lescastcodeurs.com (https://lescastcodeurs.com/2021/12/20/lcc-269-la-la-log4j/) : 
- le lien https://traffic.libsyn.com/lescastcodeurs/LesCastCodeurs-Episode-269.mp3 est en 404,
- il manque le titre.

**Comment by marcwrobel** [comment]
Pour info :
- tout ce qui est commité sur master est automatiquement publié sur https://lescastcodeurs.com,
- il existe une fonctionnalité de draft dans Jekyll qui sert à pouvoir commiter des posts sans les publier : https://jekyllrb.com/docs/posts/#drafts.

**Comment by glaforge** [comment]
Et en mettant en `published` à `false` dans le _front matter_ ça devrait le faire aussi ?
(vu qu'on n'a pas de répertoire `draft`)

**Comment by marcwrobel** [comment]
Oui ça marche aussi.

J'ai ajouté un répertoire `_drafts` persistant pour les prochaines fois.
