### ISSUE TITLE
Ecrire un bot slack pour aider à la création des shownotes

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lescastcodeurs.com#104]
Aujourd'hui, nous entrons les news dans un channel slack et une personne écrit un résumé dans le thread de chaque message de news. C'est top parce que c'est partagé par tous et qu'on voit où on en est niveau nouvelles. Et il y a moins de friction que d'entrer les news dans le wiki directement ce qui est vital.

Mais la conversion des entrées slack vers le wiki / shownote de l'épisode est manuel et beaucoup de copier coller. On pourrait automatiser ça (en tous cas pré categorisation) avec un bot / application slack.

**Comment by emmanuelbernard** [comment]
@marcwrobel si ça t'amuse et si tu as du temps, fais moi signe.

**Comment by marcwrobel** [comment]
@emmanuelbernard ça pourrait être sympa à faire. Pour info je n'ai jamais fait de bot slack.

Tu imagines quel genre d’interactions avec ce bot ? Un message structuré du genre "@bot, add xxx to LCC-1234", une discussion (un peu comme l'exemple sur https://api.slack.com/bot-users#responding-to-events)... ?

J'imagine aussi que ça devra être hébergé quelque part. Tu sais déjà où ?

**Comment by emmanuelbernard** [comment]
en fait aujourd'hui on ouvre un channel par épisode etpour chaque nouvelle on a :
* le message principal avec le lien vers l'article
* des details dans le fil de discussion qui correspondent aux points que tu vois sous chaque nouvelles.

Donc le bot pourrait etre appelé à la fin du genre @lcc generate-shownotes et paf il lit les messages du channel et sort le markdown dans github.

Pour l'hébergement, soit on deploie dans un petit VPS chez OVH, soit @glaforge nous trouve un micro budget pour des [google cloud function](https://cloud.google.com/functions/docs/tutorials/slack), et si tu écris la fonction en Quarkus (via [l'approche portable Funqy](https://quarkus.io/guides/funqy-gcp-functions), tu fais le jackpot bingo des cast codeurs :)

**Comment by emmanuelbernard** [comment]
Exemple de news.

![Screenshot 2022-06-01 at 22 32 45](https://user-images.githubusercontent.com/300760/171496387-93328023-ccf3-4974-a71f-450fbd83837a.png)

Aujourd'hui on met tous les points dans le meme message par ce que ca aide le copier coller mais c'est pénible.

**Comment by marcwrobel** [comment]
Essayons d'atteindre le jackpot bingo des cast codeurs alors ! Je n'ai presque aucune connaissance de Quarkus, des Google cloud function, ni de l'API Slack : ça devrait donc être sympa à faire.

Les deux premiers millions d'appels sont gratuits d'après https://cloud.google.com/functions/pricing#invocations, donc on ne devrait même pas avoir besoin d'un micro-budget de @glaforge. Il faudra par contre s'arranger sur le compte GCP à utiliser quand se sera en prod.

Merci pour les liens.

**Comment by marcwrobel** [comment]
Rien à voir avec le sujet mais je suis en train de tester [asdf](https://asdf-vm.com/) (sympa comme outil !). J'en ai donc profité pour créer un plugin pour Quarkus CLI (https://github.com/marcwrobel/asdf-quarkus) avant de commencer.

**Comment by emmanuelbernard** [comment]
Ah interessant, moi je traite Quarkus comme evergreen et utilises toujours la dernière version ;P

**Comment by marcwrobel** [comment]
J'essaie aussi de toujours utiliser les dernières versions quand c'est possible et relativement facile. J'utilise asdf principalement pour la facilité d'installation / désinstallation des différents outils.

Ces dernières années j'ai souvent eu besoin d'utiliser Java / Maven / Node.js sur différents projets. L’intérêt de asdf par rapport à d'autres outils du même genre que j'ai pu tester (SDKMAN!, nvm, rvm...) est qu'il n'est pas spécifique à une techno, et ça facilite beaucoup les choses.

**Comment by marcwrobel** [comment]
Nouveau projet GitHub créé : https://github.com/lescastcodeurs/lcc-slack-bot.

**Comment by marcwrobel** [comment]
Du coup pour résumer on partira sur une application Quarkus qui sera déployée sous la forme d'une Google Cloud Function. 

L'application devra réagir à la slack slash command `@lcc generate-shownotes`. À partir de là :
- elle lit l'ensemble du channel slack, qui sera structuré de la manière suivante :
  - un épisode = un channel,
  - un lien = un thread : le premier message du thread est le lien, les réponses sont les points associés au lien.
- elle génère le markdown nécessaire pour les show notes (certainement en utilisant le `Template-news`),
- elle créé une nouvelle page dans le wiki du projet GitHub lescastcodeurs.com avec comme contenu le markdown généré à l'étape précédente.

Les liens utiles pour la création de l'application Quarkus :
- [Quarkus - Funqy Google Cloud Functions](https://quarkus.io/guides/funqy-gcp-functions)
- [Quarkus and the Google Cloud Functions](https://www.loicmathieu.fr/wordpress/en/informatique/quarkus-et-les-google-cloud-functions/)

Les docs utiles pour la création de la Slack Slash Commands :
- [Enabling interactivity with Slash Commands](https://api.slack.com/interactivity/slash-commands)
- [Cloud functions - Slack Tutorial - Slash Commands](https://cloud.google.com/functions/docs/tutorials/slack)

Les docs utiles pour la création de la page wiki sur GitHub :
- [GitHub docs - Create or update file contents](https://docs.github.com/en/rest/repos/contents#create-or-update-file-contents)
- [Update a GitHub project wiki through the GitHub API](https://stackoverflow.com/questions/2402413/update-a-github-project-wiki-through-the-github-api)

**Comment by marcwrobel** [comment]
@emmanuelbernard je me suis un peu perdu dans la doc de Slack. Du coup j'ai commencé en utilisant leur framework, [Bolt](https://api.slack.com/bolt). Ça a l'avantage d'être simple et de prendre en charge toutes les questions liées à la sécurité.

J'ai démarré les devs sur https://github.com/lescastcodeurs/lcc-slack-bot. Pour le moment j'utilise le [Socket Mode](https://api.slack.com/apis/connections/socket) car ça permet d'avoir un bot fonctionnel sans devoir exposer un endpoint HTTP. Bolt propose aussi une intégration Google Cloud Functions, à voir si ça serait pas mieux d'utiliser ça à terme plutôt qu'une approche plus manuelle.

Pour le moment j'ai un bot fonctionnel mais qui ne fait pas grand chose. Prochaine étape : récupérer l'historique Slack afin de générer le markdown de la page wiki.

**Comment by emmanuelbernard** [comment]
Ton résumé est bon.
Pour les 3s, en fait c'est une commande fire and forget dans le sens où les shownotes seraient générées dans le wiki github par exemple et pas retournée a la commande. Je ne sais pas si ca donne des libertés.

J'avais vu bolt mais ils utilisent OKHTTP (je crois) et une version qui clashait avec le sbom Quarkus et donc la version n'était pas forcément compilable en natif. Mais c'est peut etre le chemin necessaire.

**Comment by marcwrobel** [comment]
Pour ce que tu dis sur les 3s il faudra que je teste (cf. https://api.slack.com/legacy/interactive-messages#responding_right_away). Pour le moment je balance un événement et je traite la génération des show notes à part.

Pour info ça prend pas mal de temps (des fois plus de 2s) car il y a besoin de pas mal d'appels distincts pour tout faire : 
- 1 appel pour récupérer tous les messages de premier niveau du channel,
- 1 appel par thread de message pour récupérer les replies,
- 1 appel à l'API GitHub pour publier les show notes,
- 1 dernier appel à Slack pour publier un _message de fin_ avec l'URL GitHub

Pour mes tests je retournais au début le markdown directement dans un message du channel. Pour info il y a une limite à la taille du message assez basse (en tout cas trop basse pour les show notes) et, de plus, Slack interprète en partie le markdown. Donc, même si ça n'est pas ce qu'on veut faire, ça n'est même pas une solution de repli.

En ce qui concerne bolt ils utilisent toujours okhttp (https://mvnrepository.com/artifact/com.slack.api/slack-api-client/1.22.3). Mais je pourrais je pense réécrire relativement facilement les requêtes avec un simple `java.net.http.HttpClient` : elles ne me semblent finalement pas très compliquées.

Sinon j'ai pas mal avancé. Pour le moment :
* je récupère tous les messages,
* je formate tout ça dans un document en markdown (je dois encore retravailler cette partie),
* je publie ça dans un dépôt GitHub.

Si tu as du temps et que tu veux commencer à tester tu peux jeter un coup d’œil à https://github.com/lescastcodeurs/lcc-slack-bot.

Pour publier ça dans le wiki ça risque d'être compliqué. Comme dit sur https://stackoverflow.com/questions/2402413/update-a-github-project-wiki-through-the-github-api ça n'est pas possible via les APIs. J'ai fait quelque tests en suffixant le nom du dépôt par `.wiki` et `.wiki.git` dans l'URL (les suffixes utilisés lorsqu'on veut cloner le dépôt contenant le wiki) mais ça ne fonctionne pas. Du coup le seul moyen de mettre à jour programmatiquement le wiki est de faire un clone du dépôt, commiter les show notes, et pusher. Ça m'a l'air un peu chiant à faire.

Du coup est-ce qu'il serait envisageable de publier ça dans un dépôt privé à la place (il ne resterait alors qu'un copier/coller à faire) ? Ou éventuellement de convertir le wiki en un dépôt GitHub à part (et donc pas de copier/coller) ?

**Comment by emmanuelbernard** [comment]
Ce qui est pratique dans le wiki c'est que une fois les shownotes générées, chacun peut éditer les jours ou heures avant l'épisode. Et moi pour la publication je repars de ça.
On peut faire un repo (pas forcément privé) tant que c'est aussi facilement éditable. Vu les outils d'édition de GitHub web on ne va pas perdre beaucoup.

**Comment by marcwrobel** [comment]
Ok, du coup j'ai presque une première version de disponible : il me reste à régler https://github.com/lescastcodeurs/lcc-slack-bot/pull/15 et à mettre en place ce qu'il faut pour livrer une version. Cette première version permettra de vérifier le fonctionnement du bot.

Je pense que je la déploierais sur mon serveur, ça sera plus simple. Je peux aussi créer le dépôt dans l'organisation `lescastcodeurs`. Par contre il faudrait voir comment on procède pour la Slack app :

1. Soit on la créé dans l'espace de travail Slack utilisé par l'équipe des Cast Codeurs ?
2. Ou alors je t'invite @emmanuelbernard dans l'espace de travail Slack que j'utilise pour mes tests ?

J'ai tendance à préférer la première solution car elle permet de tester le bot sur de "vraie" données. Mais en même temps ça risque de spammer tout le monde et il faudra que le propriétaire de cet espace créé le bot (ou me donne les droits nécessaires pour que je puisse le faire). Tu préfères fonctionner comment @emmanuelbernard ?

Ensuite si on est bon sur le fonctionnement il faudra, pour se rapprocher un peu des Google Cloud Functions et permettre la compilation native (bloquée actuellement par OKHTTP)  :
- remplacer les utilisations de `com.slack.api.Slack` par un client HTTP Java basique,
- remplacer la `SocketModeApp` par une WebApp classique et voir comment la déclarer sur Slack
- supprimer la dépendance à Bolt

**Comment by marcwrobel** [comment]
Le bot est en place depuis quelques temps. Il reste des choses à faire mais ce sera pris en charge au travers de tickets sur https://github.com/lescastcodeurs/lcc-slack-bot.
