### ISSUE TITLE
Rendu du bandeau menu incorrect quand le fenetres est plus petite

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lescastcodeurs.com#111]
(sur Firefox et Safari)

![Screenshot 2022-11-02 at 16 55 30](https://user-images.githubusercontent.com/300760/199538696-b0c4f600-bdf6-4cc4-8c3b-35766ce39ea3.png)

**Comment by marcwrobel** [comment]
Tu t'attends à avoir le menu "hamburger" plus tôt c'est ça ?

**Comment by emmanuelbernard** [comment]
C'est une bonne question. Oui ça me parait mieux que de faire passer les titres sur deux lignes.
