### ISSUE TITLE
Mise en place de Fairlytics

### ISSUE THREAD

**Issue by marcwrobel** [lescastcodeurs/lescastcodeurs.com#115]
À cause des problématiques liées au RGPD l'intégration Google Analytics avait été supprimée sans être remplacée (voir #95).

À l'écoute de https://www.podbean.com/media/share/dir-swj6a-16f04fe9 j'ai découvert l'outil [open source](https://github.com/Herve07h22/fairlytics-community) [Fairlytics](https://fairlytics.tech/). Il permet de faire de la mesure d'audience sans devoir ajouter de bannière. Il existe de plus une offre SaaS gratuite et hébergée en France (OVH) qui permet de démarrer facilement sans avoir à installer quoique ce soit : https://fairlytics.tech/.

J'ai testé sur mon site (https://github.com/marcwrobel/marcwrobel.github.io/issues/41) : c'est basique mais ça fait bien le job. Ça t'intéresserait de le mettre en place sur https://lescastcodeurs.com/ @emmanuelbernard ?

**Comment by emmanuelbernard** [comment]
On peut, cela dit on n'en a pas vraiment besoin, le site web n'est pas notre coeur de valeur.

**Comment by emmanuelbernard** [comment]
Par contre ils font du 1-1 entre une IP et son sha1, donc ils ne salent pas ou en tous cas pas avec un sel different par IP, donc c'est reversible, il suffit de connaitre le sel ou de le brute forcer

**Comment by marcwrobel** [comment]
> On peut, cela dit on n'en a pas vraiment besoin, le site web n'est pas notre cœur de valeur.

Ok, si on n'en a pas vraiment besoin autant s'en passer.

> Par contre ils font du 1-1 entre une IP et son sha1, donc ils ne salent pas ou en tous cas pas avec un sel different par IP, donc c'est reversible, il suffit de connaître le sel ou de le brute forcer

Effectivement, il y a peut être un trou dans la raquette. Je n'ai pas regardé comment ça fonctionnait, et en lisant la description j'ai du mal à savoir ce qu'il y a derrière le terme "chiffrement".
