### ISSUE TITLE
Discuter le repertoire video avec Marc

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lescastcodeurs.com#41]

**Comment by emmanuelbernard** [comment]
La todo fait reference au répertoire vidéo, mais je n'ai pas vu de tel répertoire sur la source de l'ancien site. Tu fais référence à quoi ?

**Comment by emmanuelbernard** [comment]
@marcwrobel ^

**Comment by marcwrobel** [comment]
@emmanuelbernard, aucune idée. Ce todo était l'un des tiens ;). Cf. https://github.com/lescastcodeurs/lescastcodeurs.com/commit/cd1e930fe43f62a794a87cde4dc04798b8784e7f.
