### ISSUE TITLE
Déplacer feed.atom vers feed-intern.atom

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lescastcodeurs.com#44]
Je ne me rappelle plus la raison pour avoir mis la feed concrete sur feed-intern.atom et avoir un redirect dans .htredirect mais il devais y avoir une raison. @marcwrobel dans tes explorations de l'ancien code, tu as vu des indices ?

C'est un peu conservatif mais je me dis qu'on pourrait garder cette structure au cas où.

**Comment by marcwrobel** [comment]
Non, aucune idée mais à priori ça a toujours été comme ça :
```
(35-jekyll) mwrobel@l1:~/projects/lescastcodeurs.com$ git log -S feed-intern
...

commit 1f4469c761da8d684953e4a1584b91238348bb5b
Author: Emmanuel Bernard <emmanuel@hibernate.org>
Date:   Mon May 11 11:00:02 2015 +0200

    Make it work already: the feed feed/ redirects are a true mystery to me

commit 67d27895d69522c1c3b56572e0ba779d89daadf2
Author: Emmanuel Bernard <emmanuel@hibernate.org>
Date:   Mon May 11 10:05:14 2015 +0200

    Fix feed redirect to hide feed-intern

commit 82e5855a9d4f87cfd4591ec837f6539edae7b96c
Author: Emmanuel Bernard <emmanuel@hibernate.org>
Date:   Sat May 9 13:22:54 2015 +0200

    Fix the /feed/ URL
(35-jekyll) mwrobel@l1:~/projects/lescastcodeurs.com$ git show 82e5855a9d4f87cfd4591ec837f6539edae7b96c
commit 82e5855a9d4f87cfd4591ec837f6539edae7b96c
Author: Emmanuel Bernard <emmanuel@hibernate.org>
Date:   Sat May 9 13:22:54 2015 +0200

    Fix the /feed/ URL

```

**Comment by marcwrobel** [comment]
@emmanuelbernard, c'est fait. Pour info lors du lancement du site en local le lien dans le head des pages est '/feed.atom' comme actuellement (mais du coup c'est une 404 car la redirection du .htaccess n'est pas appliquée).

On pourra peut-être essayer un jour d'inverser la redirection (/feed.atom -> /feed-intern.atom) histoire de simplifier les choses.
