### ISSUE TITLE
Feed.atom differences

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lescastcodeurs.com#45]
`<id>https://lescastcodeurs.com</id>` et pas `<id>https://lescastcodeurs.com/feed.atom</id>` c'est improtant pour les RSS readers je pense.

`<title type="html">Les Cast Codeurs Podcast</title>` et pas `<title type="html">Les Cast Codeurs Podcast | </title>`

`<link rel="enclosure" type="audio/mpeg" title="LCC 242 - Les Applets, 20 ans trop tôt" length="75018942" href="/LesCastCodeurs-Episode-242.mp3" />` et pas `<link rel="enclosure" type="audio/mpeg" title="LCC 242 - Les Applets, 20 ans trop tôt" length="75018942" href="https://traffic.libsyn.com/lescastcodeurs/LesCastCodeurs-Episode-242.mp3" />`

Je vois pas mal d'espaces non necessaires et de lignes vides dans le fichier. C'est pas grave en soit mais la feed est grosse et consomme de la bande passante pour le server et les clients.
Sinon, je choix de l'ordres des balises est curieux mais c'est esthétique ;)

Sinon ca passe xmllint ce qui est cool ;)

**Comment by emmanuelbernard** [comment]
@marcwrobel quelques retours sur le contenu de la feed et ses différences avec l'originale

**Comment by marcwrobel** [comment]
@emmanuelbernard j'ai réorganisé les balises et supprimé les espaces inutiles. Je m'était basé sur le template de https://github.com/jekyll/jekyll-feed sans trop le changer.

**Comment by marcwrobel** [comment]
@emmanuelbernard autre différence : le flux ne contenait que 10 entrée. J'ai modifié pour aller jusqu'à 10000 entrée (comme actuellement - https://github.com/lescastcodeurs/lescastcodeurs.com/blob/ff0ddcec0165056d4111e888336db5a0878ae9e2/_ext/pipeline.rb#L15).
