### ISSUE TITLE
Enlever la reference a Flattr dans en parler

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lescastcodeurs.com#46]

**Comment by marcwrobel** [comment]
@emmanuelbernard, Flattr est aussi référencé sur pas mal de posts dans le paragraphe de fin "Nous contacter", comme par exemple sur https://lescastcodeurs.com/2020/07/08/lcc-235-interview-micro-services-avec-@ygrenzinger-et-@khaledsouf/.

Est-ce qu'on ne devrait pas inclure le paragraphe 'Nous contacter', qui est à la fin de chaque post d'annonce d'un nouveau podcast, directement dans le layout des blog-post (en ne ciblant que les podcast) ? Ça te permettrait de :
- ne plus avoir à écrire à chaque fois ce paragraphe,
- de mettre à jour ce paragraphe en une fois quand c'est nécessaire.

**Comment by marcwrobel** [comment]
@emmanuelbernard, ne devrait-on pas ajouter un lien vers la page "En parler" dans le bloc "Nous soutenir" de la sidebar de droite ?

**Comment by emmanuelbernard** [comment]
> @emmanuelbernard, ne devrait-on pas ajouter un lien vers la page "En parler" dans le bloc "Nous soutenir" de la sidebar de droite ?

non c'est pas si important et la promo active de cette page n'est pas nécessaire.

**Comment by emmanuelbernard** [comment]
> @emmanuelbernard, Flattr est aussi référencé sur pas mal de posts dans le paragraphe de fin "Nous contacter", comme par exemple sur https://lescastcodeurs.com/2020/07/08/lcc-235-interview-micro-services-avec-@ygrenzinger-et-@khaledsouf/.
> 
> Est-ce qu'on ne devrait pas inclure le paragraphe 'Nous contacter', qui est à la fin de chaque post d'annonce d'un nouveau podcast, directement dans le layout des blog-post (en ne ciblant que les podcast) ? Ça te permettrait de :
> 
>     * ne plus avoir à écrire à chaque fois ce paragraphe,
> 
>     * de mettre à jour ce paragraphe en une fois quand c'est nécessaire.

En fait la meme source est aussi utilisée pour le flux RSS du podcast qui arrive avant le site web. Donc je le laisse dans le contenu.
