### ISSUE TITLE
Revue de la page 'Soutenir' pour remplacer les montants en dollars en montants en euros

### ISSUE THREAD

**Issue by marcwrobel** [lescastcodeurs/lescastcodeurs.com#47]
Maintenant que patreon permet de payer en euros, la page ['Soutenir'](https://lescastcodeurs.com/soutenir/) (section _Pourquoi vous n’avez pas de tiers de contribution plus bas / plus haut ?_) devrait-elle être revue pour remplacer les montants en dollars en montants en euros ?

**Comment by emmanuelbernard** [comment]
Carrément, merci de l'avoir vu.
