### ISSUE TITLE
Ajout d'une fonctionnalité de recherche sur le site

### ISSUE THREAD

**Issue by marcwrobel** [lescastcodeurs/lescastcodeurs.com#61]
@emmanuelbernard serais-tu intéressé par une fonctionnalité de recherche basique sur le site ? Cela permettrait de compléter (ou remplacer ?) la page [Liste des épisodes](https://lescastcodeurs.com/episodes/).

L'idée serait de ne pas s'appuyer sur des services externes mais d'intégrer https://github.com/christian-fei/Simple-Jekyll-Search car c'est facile / rapide à faire et à maintenir.  Cette intégration est basique dans le sens où :
- l'indexe de recherche est créé une fois pour toute à la création du site (JSON templaté par Jekyll),
- la recherche se fait côté navigateur via une nouvelle page / le javascript fourni par Simple-Jekyll-Search,
- les possibilité du moteur de recherche de Simple-Jekyll-Search sont donc relativement limitées.

Si tu veux voir à quoi ça peut ressembler : https://www.marcwrobel.fr/search.html.

**Comment by emmanuelbernard** [comment]
Oui ca serait bien, j'ai toujours voulu implémenter quelque chose comme ca pour les sites statiques générés mais jamais eu le temps :)
