### ISSUE TITLE
Devrait-on utiliser l'environnement PRODUCTION de Jekyll

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lescastcodeurs.com#71]
Hey @marcwrobel 

A moins que je n'ai pas vu un truc, on n'utilise pas `JEKYLL_ENV=production bundle exec jekyll build`
De ce que j'ai compris, cela impact les trucs comme Google Anaytics et disqus

Et effeectivement, je vois les analytics à ~0 depuis la semaine du 6 decembre.

On applique ^ dans `bin/build` ? Ou tu vois une contre indication ?

**Comment by marcwrobel** [comment]
Salut @emmanuelbernard, oui il faudrait ajouter JEKYLL_ENV=production au script de build.

Je n'y avais plus pensé mais c'est effectivement nécessaire pour activer Google analytics et disqus et c'est ce qui aurait dû être fait depuis le début (donc pas de contre indication).

Tu t'en occupes ?

**Comment by emmanuelbernard** [comment]
Fixed
