### ISSUE TITLE
Mise en conformité de lescastcodeurs.com avec la RGPD

### ISSUE THREAD

**Issue by marcwrobel** [lescastcodeurs/lescastcodeurs.com#95]
D'après https://www.geek-directeur-technique.com/2021/04/15/mettre-google-analytics-en-conformite-avec-le-rgpd-sans-bandeau-de-cookie il semblerait que les sites qui utilisent Google Analytics "de base" ne soient pas en conformité avec la RGPD car Google Analytics :

- utilise des cookies et que les internautes ne sont pas prévenus quand ils vont sur lescastcodeurs.com
- conserve des informations sur les utilisateurs (IP notamment)

Toujours d'après le même article il est possible d'être conforme à la RGPD tout en conservant Google Analytics et toujours sans bandeau de cookie. Mais cela se fait au prix de la richesse d'informations remontées à Google Analytics. Il faudrait en effet modifier l'appel pour avoir quelque chose dans le genre de :
```
<script async src="https://www.googletagmanager.com/gtag/js?id=VOTRE_IDENTIFIANT_GA"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'VOTRE_IDENTIFIANT_GA', {
        client_storage: 'none',
        anonymize_ip: true
    });
</script> 
```
Et avec cet appel :

- les "sessions de navigation" ne sont plus suivies
- j'imagine qu'il n'y a beaucoup moins (ou plus du tout) d'infos sur la localisation des utilisateurs, les navigateurs utilisés...

Doit-on mettre en place ce paramétrage Google Analytics sur lescastcodeurs.com pour être conforme RGPD ?

**Comment by emmanuelbernard** [comment]
Je prefererais ne pas avoir le bandeau donc +1 pour perdre de l'info.
Par contre, c'est a quadruple checker parce que tout le monde interprete differement les besoins. Si tu vois l'info de manière consistante sur plusieurs articles, +1 pour faire le changement.

**Comment by marcwrobel** [comment]
Oui, c'est un sujet compliqué.

Je clôture l'issue pour le moment, je la rouvrirais si besoin.

**Comment by marcwrobel** [comment]
Quoique avant je vais regarder ce qui est dit sur : 
* https://www.cnil.fr/sites/default/files/typo/document/GOOGLE_PRIVACY_POLICY-RECOMMENDATIONS-FINAL-FR.pdf
* https://www.clementcombes.com/blog/exemption-consentement-google-analytics/

**Comment by marcwrobel** [comment]
La CNIL semble se durcir sur le sujet : https://www.cnil.fr/fr/utilisation-de-google-analytics-et-transferts-de-donnees-vers-les-etats-unis-la-cnil-met-en-demeure.

Je suis curieux de connaître le résultat de leur _programme d’évaluation pour déterminer les solutions exemptées de consentement_. Ça permettrait de s'y retrouver un peu plus facilement car ça n'est pas simple d'avoir une vision claire de ce qu'il faudrait faire.

@emmanuelbernard si tu as plus d'infos sur le sujet, ou si tu connais quelqu'un qui serait susceptible d'avoir plus d'info, je suis preneur.

**Comment by marcwrobel** [comment]
@emmanuelbernard, la CNIL a publié un article expliquant comment utiliser Google Analytics tout en étant en conformité avec le RGPD : [Google Analytics et transferts de données : comment mettre son outil de mesure d’audience en conformité avec le RGPD ?](https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/google-analytics-et-transferts-de-donnees-comment-mettre-son-outil-de-mesure-daudience-en-conformite). Si je résume ils expliquent que pour être raccord avec la RGDP il faut proxyfier les appels à Google Analytics et pseudonymiser les données avant de les envoyer à Google. Bref c'est compliqué...

J'ai découvert au passage une FAQ, toujours de la CNIL, à ce sujet : [Questions-réponses sur les mises en demeure de la CNIL concernant l’utilisation de Google Analytics](https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/questions-reponses-sur-les-mises-en-demeure-de-la-cnil-concernant-lutilisation-de-google-analytics).

Et pour info je suis retombé sur une alternative qui a l'air sympa (et conforme au RGPD) à Google Analytics : [Plausible](https://plausible.io/) (voir aussi [5 benefits of switching from Google Analytics to Plausible](https://opensource.com/article/22/5/plausible-analytics)). Par contre malheureusement leur offre SaaS n'est pas gratuite (et est même plutôt chère pour un site comme lescastcodeurs.com - 9 € / mois - [et il n'y a pas d'offre plus abordable à l'horizon](https://github.com/plausible/analytics/discussions/1882)). Il y a toujours la possibilité d'héberger soi-même Plausible mais là le coût est déporté sur l'hébergement et la maintenance.

**Comment by emmanuelbernard** [comment]
Oui, j'ai vu passer. En y réfléchissant, je pense que la valeur de l'analytics ne vaut pas le risque ou les 9€ par mois. Donc mieux vaut qu'on enlège Google Analytics. Tu veux le faire ?

**Comment by marcwrobel** [comment]
OK, je m'en occupe.

**Comment by marcwrobel** [comment]
@emmanuelbernard c'est fait.

Je me demande si on a pas le même problème avec :
-  le CDN jsdeliver (https://www.jsdelivr.com/blog/how-the-german-courts-ruling-on-google-fonts-affects-jsdelivr-and-why-it-is-safe-to-use/),
- Disqus (https://help.disqus.com/en/articles/1886218-privacy-faq).

Je n'ai pas eu le temps de lire les liens, je te tiens au courant.

**Comment by marcwrobel** [comment]
Pour ce qui est de jsdeliver ils sont plutôt rassurants sur https://www.jsdelivr.com/blog/how-the-german-courts-ruling-on-google-fonts-affects-jsdelivr-and-why-it-is-safe-to-use/. Néanmoins ils recommandent quand même pour minimiser les risques de mettre en place une politique de confidentialité et d'éventuellement recueillir le consentement des utilisateurs.

Pour Disqus à priori la mise en place d'une bannière est obligatoire (cf. https://help.disqus.com/en/articles/1886218-privacy-faq, https://www.iubenda.com/en/help/23947-disqus-gdpr-how-to-be-compliant).

Du coup je propose :
- Ne pas se poser trop de question et d'embarquer directement dans le site les dépendances externes (bootstrap, bootstrap icon...). Il faudra mettre en place un moyen simple d'effectuer les mises à jour (un script ?).
- De supprimer disqus : il y a peu de commentaires disqus sur lescastcodeurs.com. https://groups.google.com/g/lescastcodeurs est beaucoup plus utilisé.
- D'éventuellement mettre en place une nouvelle page expliquant la politique de confidentialité (est-ce que des PII sont conservées sur le serveur hébergeant lescastcodeurs.com, si oui combien de temps et à quelles fins...).

@emmanuelbernard tu en penses quoi ?

**Comment by emmanuelbernard** [comment]
Oui ca marche. Ce qu'on peut faire c'est de pointer les gens vers les google groupe via le template de la page episode

```
Pour réagir à cet épisode, venez discuter sur ...
```

**Comment by marcwrobel** [comment]
Avec le retrait de Disqus la phrase "_ou sur le site web https://lescastcodeurs.com/_" qui est mise systématiquement dans le paragraphe "_Nous contacter_" ne devient-elle pas obsolète ?

Si oui, ne faudrait-il pas mieux intégrer l'ensemble du paragraphe "_Nous contacter_" dans le template de la page episode, avec le blabla pour pointer les gens vers les google groupe, afin de pouvoir le modifier partout en même temps ? Pour info il me semble qu'on en avait déjà parlé et que tu n'étais pas pour.

**Comment by marcwrobel** [comment]
Ok. J'ai vu que tu as mis à jour le template de news. Est-ce que la phrase _ou sur le site web https://lescastcodeurs.com/_ doit être supprimée de l'ensemble des articles de news ou est-ce qu'on laisse comme ça ?

**Comment by marcwrobel** [comment]
Sinon pour les commentaires via le groupe google, plutôt que d'inclure quelque chose via un template, on pourrait juste modifier le paragraphe _Nous contacter_, par exemple comme suit :

```
Pour réagir à cet épisode, venez discuter sur le groupe Google <https://groups.google.com/group/lescastcodeurs>  
Contactez-nous via twitter <https://twitter.com/lescastcodeurs>  
[Faire un crowdcast ou une crowdquestion](https://lescastcodeurs.com/crowdcasting/)  
Soutenez Les Cast Codeurs sur Patreon <https://www.patreon.com/LesCastCodeurs>
``

**Comment by emmanuelbernard** [comment]
Je ne te suis pas trop là, tu pourrais me détailler un peu plus comment tu vois les choses.

**Comment by marcwrobel** [comment]
Je reprend tout histoire que ce soit plus clair (j'aurais peut-être dû faire un ticket par sujet). Le sujet est de retirer disqus, hors on aimerait rajouter une phrase du genre _Pour réagir à cet épisode...._ pour faire aller les gens vers le groupe Google s'ils veulent commenter l'épisode.

L'idée que tu avais eu étais de modifier le template des articles pour rajouter cette phrase. Si on modifie le template la phrase sera donc forcément à la fin de l'article, donc après le paragraphe "Nous contacter". Hors dans ce paragraphe on mentionne déjà le groupe Google, du coup je pense que ça risque de faire doublon.

On pourrait donc à la place juste modifier le paragraphe "Nous contacter" que tu inclus à chaque fois pour être plus clair sur le fait que pour commenter il faut aller sur le groupe Google. Je proposais donc de modifier le paragraphe par exemple comme suit : 
```
Pour réagir à cet épisode, venez discuter sur le groupe Google <https://groups.google.com/group/lescastcodeurs>  
  
Contactez-nous via twitter <https://twitter.com/lescastcodeurs>  
[Faire un crowdcast ou une crowdquestion](https://lescastcodeurs.com/crowdcasting/)  
Soutenez Les Cast Codeurs sur Patreon <https://www.patreon.com/LesCastCodeurs>
```
Si on fait ça il me faudra aussi savoir si je modifie le paragraphe "Nous contacter" sur tous les anciens articles.
