### ISSUE TITLE
Resumé des épisodes contient la date

### ISSUE THREAD

**Issue by emmanuelbernard** [lescastcodeurs/lescastcodeurs.com#98]
En regardant https://lescastcodeurs.com/episodes/

On peut voir une différence entre l'épisode 260 et 261

```
LCC 261 - Interview Doctolib avec David Gageot (29/07/2021)

Guillaume et Antonio interviewent David Gageot à propos de Doctolib, l’entreprise, mais surtout ses différents produits, l’architecture et comment elle a géré la prise des rendez-vous pour les vaccins anti-covid.

Enregistré le 30 Juin 2021

LCC 260 - L'épisode généré par intelligence artificielle (27/07/2021)

Antonio, Guillaume et Emmanuel discutent de pleins de choses dont des analyses de l’écosystème de la JVM, de la generation de code via intelligence Artificielle avec CoPilot, mais pas que
```

"Enregistré le ..." est visible sur 261. Je n'ai pas vu de différence spécifique dans le document qui explique la variation. Ça serait bien d'investiguer pour supprimer "enregistré le" vu qu'une date est déjà là la fin du titre.

**Comment by emmanuelbernard** [comment]
@marcwrobel si tu as un peu de temps et d'envie, sinon je regarderai à l'occasion.

**Comment by marcwrobel** [comment]
Étrange en effet. Seul le premier paragraphe devrait être conservé d'après la doc (https://jekyllrb.com/docs/posts/#post-excerpts) et je ne vois pas non plus de différence entre les épisodes 260 et 261.

Je jetterai un coup d'œil courant de semaine prochaine : pas facile de regarder ça sur un téléphone 😋.

**Comment by marcwrobel** [comment]
@emmanuelbernard, la date était incluse dans le résumé des articles 259 et 261 car la ligne séparant le résumé et la date d'enregistrement contenait un caractère d'espacement. C'est corrigé.
